meilisearch/meilisearch-js

src/__tests__/indexes.ts
src/__tests__/meili.ts
src/indexes.ts
src/types.ts

**CHANGES:**
Src/Indexes.ts 
- Renamed `browse` function with `getDocuments`
- Moved `getDocuments` to be closer to other document methods
- FIX: fixed a bug on the document delete URL that was badly formatted
- Removed batchWriteDocument which doesn’t exist anymore
- Renamed `clearAllDocuments` with `deleteAllDocuments`
Src/test/
- Changed format of tests with async jest functions
- Added semi-colon at the end of every command
- Added testing on schema
- Added testing on documents delete
- Changed the dataset to a smaller one for testing purpose
Src/types
- Renamed `BrowseParams` with `GetDocumentsParams`

Documents route done and tested

---

examples/test.js
package.json
src/__tests__/indexes.ts
src/__tests__/meili.ts
src/index.ts
src/indexes.ts
src/types.ts
yarn.lock

Since the new version of typescript test files are tested simultaneously. Which created conflict on the MeiliSearch server calls.
Also, the `yarn format:fix` is not executing automatically when building. It has to be done manually before building. If there is a style error the build is not completed without more explanations than `exit code 1`. If you have this error it means you need to `yarn format:fix`.
With this PR the tested are done one after the other and `yarn build` also fixes the linting problems.

FIX: build and testing

---

README.md
config/jest.config.js
examples/search_example.js
src/__tests__/indexes.ts
src/indexes.ts
src/types.ts

Change search route from 
`meili.Index('xxx').search(options: Types.SearchParams): Promise<Types.SearchResponse>`
in which `q` was a key in SearchParams.
to 
`meili.Index('xxx').search(query: string, options?: Types.SearchParams): Promise<Types.SearchResponse>`

Change search route parameters

---

src/indexes.ts
src/types.ts
tests/documents_tests.ts

Added tests for documents. 
All tests are done on every API key and on both an index containing a primary key from the start and on an index containing no primary key.

Documents tests

---

src/errors/meilisearch-error.ts
src/errors/meilisearch-timeout-error.ts
src/indexes.ts
src/meili-axios-wrapper.ts
src/types.ts
src/utils.ts
tests/wait_for_pending_update_tests.ts

In this PR 
* Some styling fixes
**WaitForPendingUpdate** function, based on this issue: meilisearch/integrations-guides#1
With its associated tests.
- The base MeiliSearch error is now called `MeiliSearchApiError`. 
- The timeout error in wait for Pending update is called `MeiliSearchTimeOutError`

Wait for pending update and error naming

---

tests/accept_new_fields_tests.ts
tests/displayed_attributes_tests.ts
tests/distinct_attribute_tests.ts
tests/documents_tests.ts
tests/meilisearch-test-utils.ts
tests/ranking_rules_tests.ts
tests/search_tests.ts
tests/searchable_attributes_tests.ts
tests/settings_tests.ts
tests/stop_words_tests.ts
tests/synonyms_tests.ts
tests/update_tests.ts
tests/wait_for_pending_update_tests.ts

I have removed all the sleeps in all the javascript tests and replaced them with 
```javascruot
await client.getIndex(index.uid).waitForPendingUpdate(updateId)
```
And **bonus**: It is so much faster!

Replace sleep with wait for update

---

README.md

Hi there, I found a typo in the readme :)

doc/fix-typo-docker-run: fix typo in readme part 'Run MeiliSearch'

---

src/types.ts
tests/search_tests.ts
tests/settings_tests.ts

Facetfilter were typed as follow: 
```javascript
facetFilters? : string[]
```
This is in contradiction with how facetFilters expect as input: 
```
facetFilters: ['genre:romance', ['genre:thriller', 'genre:comedy']],
```
now it is declared the following way: 
```
export type FacetFilter = string | FacetFilter[];
​
export interface SearchParams {
// ... 
facetFilters?: FacetFilter[]
}
```
I also added `attributesForFaceting` which was not present in the settings object!

Fixes types for facetfilter

---

.code-samples.meilisearch.yaml

- Fixes `get keys` example in docs
- Also fixes an error in filtering_guide_2 and filtering_guide_4 examples
Closes #444

Fix keys examples in docs

---

package.json

Because we want our library to be usable on browser and in node we should use umd format and not cjs as the "main" in package.json

Main to UMD instead of CJS

---

.github/release-draft-template.yml

If you agree with this @bidoubiwa, I add the label `dependencies` as a label to skip the changelogs in the release drafter.
So, you don't have to add the `skip-changelog` label every time that Dependabot does a PR (since it's many times a day.....) as I did this morning for each new PR (cf the picture below):
Dependabot adds automatically the `dependencies` label, and with this PR you will not have to add the `skip-changelog` label for the Dependabot PR anymore.

Add dependencies label to exclude-labels in the release drafter

---

src/index.ts
src/meili-axios-wrapper.ts
src/meilisearch.ts
src/types.ts

Make the code consistent with `MeiliSearch` name.

Rename Meilisearch class into MeiliSearch in Typescript files

---

src/types.ts

fixes: #482 
Because facetFilter only has a max deepness of `2` the following is still possible with this new type: 
Valid:
```javascript
facetFilters: ['genre:thriller', [['genre:comedy'], 'genre:romance']],
```
Not valid:
```javascript
facetFilters: ['genre:thriller', [[['genre:comedy'], 'genre:romance']]],
```

Remove circular reference in type

---

tests/client_tests.ts
tests/settings_tests.ts

The tests currently fail because of:
- [this issue](https://github.com/meilisearch/MeiliSearch/issues/798) for the distinct-attributes
I removed the `cpu` test as the sys-info will be removed soon

Update tests according to bump meilisearch v0.12.0

---

src/types.ts

The API is expecting acceptNewFields but the typescript type here was using indexNewFields.
This is a redo of #492

Fix: Updated settings type to fix misnamed acceptNewFields

---

rollup.config.js

With the rollup updates, a new warning was raised during build:
```bash
(!) Entry module "src/meilisearch.ts" is implicitly using "default" export mode, which means for CommonJS output that its default export is assigned to "module.exports". For many tools, such CommonJS output will not be interchangeable with the original ES module. If this is intended, explicitly set "output.exports" to either "auto" or "default", otherwise you might want to consider changing the signature of "src/meilisearch.ts" to use named exports only.
```
To avoid this confusion I have added the export mode we use in the rollup config.

Add export mode to rollup config

---

.code-samples.meilisearch.yaml
README.md
src/meilisearch.ts
src/types.ts
tests/client_tests.ts

fixes: #504 
The tests in the CI will fail until MeiliSearch `v0.13.0` is out.
Currently, tested with the `v0.13.0rc0`, tests are failing because of:
- the error message changed #531 
- `genre: 'fantasy'` missing in search tests, fixed in: #529 
-  <s>Settings tests fixed in #530</s> -> merged

Remove sys-info and sys-info pretty

---

tests/client_tests.ts
tests/documents_tests.ts

The tests in the CI will fail until MeiliSearch v0.13.0 is out.
Currently, tested with the v0.13.0rc0, tests are failing because of:
- genre: 'fantasy' missing in search tests, fixed in: #529
- <s>404 on get system info tests: fixed in #528</s> -> merged

Change tests error messages

---

.code-samples.meilisearch.yaml

Question @bidoubiwa:
Why are we using the global settings route to update one specific setting in most examples? It's a louder way to write it. 
Instead of only:
```js
client.getIndex('movies').updateDistinctAttribute('bla')
```
we have currently:
```js
client.getIndex('movies').updateSettings({ distinctAttribute: 'bla' })
```

Fix settings examples

---

src/meili-axios-wrapper.ts
src/types.ts

This PR adds an additional parameter `headers` to the Config and changes the way the AxiosInstance is created. 
This way the user can supply additional headers that are required by the local infrastructure (e.g. an API Gateway).
Additionally, i added the correct `Content-Type` Header. At the moment requests use the `x-www-form-urlencoded` ContentType.

allow for additional header and set correct content type for requests

---

src/meili-axios-wrapper.ts
tests/client_tests.ts
tests/index_tests.ts
tests/meilisearch-test-utils.ts

This PR has its base from this PR #546 
Add tests that tries out custom headers.
I also renamed `client_tests.ts` to `index_tests.ts` and created a new `client_tests.ts` that specifically tests the MeiliSearch object.
Any suggestion for a more indepth test is welcome.
Merge this after: #546

Add client tests

---

README.md
tests/index_tests.ts

- Update compatibility in README.md
- Fixed error message failing test.
- Tested against [v0.14.0rc0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.14.0rc0)

MeiliSearch Bump to v0.14.0

---

src/utils.ts

Hey, this is a pr for issue #581 
I used one reducer to get the job done instead of using the delete operator (which warns Injection sink) or piping from a filter.
I also changed the type of the `obj` from `object` to `Record`.

replaced Object.fromEntries() to support node < v12.0

---

.code-samples.meilisearch.yaml

Just to keep documentation tidy, the list of parameters should have the same order in the different SDKs examples (using cURL as reference). :)
https://docs.meilisearch.com/guides/advanced_guides/settings.html#example-3

Change list order in params for faceted_search_update_settings_1

---

tests/index_tests.ts
tests/search_tests.ts

Update tests and add a test for the placeholder when the query is empty.
This PR:
- fails in this CI because the MeiliSearch's release v0.15.0 is not out
- should work locally with the [prerelease v0.15.0rc2](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0rc2)

Update tests for MeiliSearch v0.15.0

---

README.md
src/meilisearch.ts
src/types.ts
tests/dump_tests.ts

This PR adds features to manage `dumps` introduced in v0.15

Add `dumps` features

---

src/http-requests.ts
tests/client_tests.ts

In this PR we resolve a problem that has been explained on slack where if the host URL had a path ( domain + slash something ) the package would ignore the path and just keep the domain.
Tests have been added to ensure this will not happen again

Resolve path removal of host url

---

README.md

According to MeiliSearch Documentation v0.15, the value of the attribute `attributesToHighlight` should take an array of string.
However, current example inside the Readme.md file use value `'*'` instead of `['*']` and may be causing some misconfiguration  related to the search functionality.

Fixing documentation example issue, related to attribute `attributesToHighlight`

---

src/errors/meilisearch-api-error.ts
src/errors/meilisearch-communication-error.ts
src/errors/meilisearch-error.ts
src/errors/meilisearch-timeout-error.ts

This PR fix the non-standard (V8) `captureStackTrace` method call in the custom error instance.
Since the method `captureStackTrace` is non-standard, non V8 browsers (e.g., Safari) throws another error like: `Error.captureStackTrace is not a function. (In 'Error.captureStackTrace(_this, MeiliSearchCommunicationError)', 'Error.captureStackTrace' is undefined)`
_Links:_
[MDN | Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

Fix the non-standard (V8) `captureStackTrace` method call in the custom error instance

---

src/types.ts
tests/attributes_for_faceting_tests.ts
tests/displayed_attributes_tests.ts
tests/distinct_attribute_tests.ts
tests/documents_tests.ts
tests/dump_tests.ts
tests/get_or_create_tests.ts
tests/index_tests.ts
tests/ranking_rules_tests.ts
tests/search_tests.ts
tests/searchable_attributes_tests.ts
tests/settings_tests.ts
tests/stop_words_tests.ts
tests/synonyms_tests.ts
tests/typed_search_tests.ts
tests/update_tests.ts
tests/wait_for_pending_update_tests.ts

This PR updates the error handling in tests, so that they do not rely on error messages anymore  and uses `errorCode` instead.
Resolve #623

Update error handling in tests (message -> errorCode)

---

README.md
package.json
src/http-requests.ts
src/index.ts
src/types.ts
tests/search_tests.ts
yarn.lock

This PR adds the ability to insert additional config into the search request, e.g., `signal` to abort the request.
Resolve #630

Add ability to abort search request

---

tests/search_tests.ts

Change the import of `abort-controller` library to a more safe way where only the needed variable is imported.

Change import to a more safe way

---

.code-samples.meilisearch.yaml
README.md
src/meilisearch.ts
src/types.ts
tests/dump_tests.ts

Related to this issue: https://github.com/meilisearch/integration-guides/issues/52
This PR:
- gathers the changes related to the next release of MeiliSearch (v0.16.0) so that this package is ready when the official release is out.
- should pass the tests against the [latest prerelease of MeiliSearch](https://github.com/meilisearch/MeiliSearch/releases). This should be tested locally.
- might eventually fail until the MeiliSearch v0.16.0 is out.
⚠️ This PR should NOT be merged until the MeiliSearch's next release (v0.16.0) is out.

Changes about the MeiliSearch's next release (v0.16.0)

---

CONTRIBUTING.md

Without this PR, meilisearch does not start and shows the following error message:
```
error: The argument '--no-analytics <no-analytics>' requires a value but none was supplied
```

Fix docker run documentation

---

.github/release-draft-template.yml
.github/workflows/pre-release-tests.yml
.github/workflows/tests.yml

Add CI for the pre-release PRs = PRs to `bump-meilisearch-v*` during the pre-release week of MeiliSearch. This CI will run the tests against the MeilliSearch RC instead of the MeiliSearch `latest`.
For each PR to `bump-meilisearch-v*`:
- the `linter-check` job will run
- the `integration-tests-against-rc` job will run
- the `integration-tests` job will be skipped
- the required jobs (for merging) in the settings will be: `linter-check` and `integration-tests-against-rc`
For each **push** to `bump-meilisearch-v*`:
- the `linter-check` job will run
- the `integration-tests-against-rc` job will run
- the `integration-tests` job will run
- the required jobs (for merging) in the settings will be: `linter-check` and `integration-tests`
For any other event (PRs and pushes):
- the `linter-check` …

Add pre release CI

---

package.json

`jsnext:main` is deprecated: https://github.com/rollup/plugins/pull/81#issuecomment-562956077
Only rollup used to use it but rollup just decided to remove it as well: https://github.com/rollup/plugins/pull/85
Should be merged after: https://github.com/meilisearch/meilisearch-js/pull/709

Remove jsnext main

---

tests/env/express/jest.config.js
tests/env/express/jest.setup.js
tests/env/express/tests/client.test.js

Because #713 also timeoud like usual I dig into the same problem again. 
I think maybe it is due to the fact that it is not the `tests` that timeout but the whole jest setup. 
So I tried following this stack overflow: 
https://stackoverflow.com/questions/49603939/message-async-callback-was-not-invoked-within-the-5000-ms-timeout-specified-by
who suggests the following: 
> But this would be specific to the test. Or you can set up the configuration file for the framework.
>
>Configuring Jest
>
>// jest.config.js
>module.exports = {
>  // setupTestFrameworkScriptFile has been deprecated in
>  // favor of setupFilesAfterEnv in jest 24
>  setupFilesAfterEnv: ['./jest.setup.js']
>}
>
>// jest.setup.js
>jest.setTimeout(30000)

Move jest timeout outside test

---

.code-samples.meilisearch.yaml
README.md
examples/node/search_example.js
src/index.ts
src/meilisearch.ts
src/types.ts
tests/attributes_for_faceting_tests.ts
tests/displayed_attributes_tests.ts
tests/distinct_attribute_tests.ts
tests/documents_tests.ts
tests/env/express/public/index.html
tests/get_or_create_tests.ts
tests/index_tests.ts
tests/meilisearch-test-utils.ts
tests/ranking_rules_tests.ts
tests/search_tests.ts
tests/searchable_attributes_tests.ts
tests/settings_tests.ts
tests/stop_words_tests.ts
tests/synonyms_tests.ts
tests/typed_search_tests.ts
tests/update_tests.ts
tests/wait_for_pending_update_tests.ts

This PR implements the following: 
- `client.getIndex()` is still usable as previously but now does an HTTP call
-  `client.getOrCreateIndex()` now does at least one HTTP call (and two sometimes)
- `index.show()` is now called `index.getRawInfo()`. 
- `index.updateIndex()` is now called `index.update`
- `index.update()` now returns an Index object instead of the JSON response of MeiliSearch
- `index.deleteIndex()` is now called `index.delete()`
- `index.fetchInfo()` returns the same instance with updated information found in MeiliSearch
- `client.index()` return an index object
- `Static Index.create()` create an index in MeiliSearch
- `primaryKey` is now a parameter of an Index Object
- `client.updateIndex()` lets you update an index without having to use the Index class
- …

Implicit index creation

---

src/http-requests.ts
src/index.ts
src/meilisearch.ts
tests/attributes_for_faceting_tests.ts
tests/client_tests.ts
tests/displayed_attributes_tests.ts
tests/distinct_attribute_tests.ts
tests/documents_tests.ts
tests/dump_tests.ts
tests/index_tests.ts
tests/meilisearch-test-utils.ts
tests/ranking_rules_tests.ts
tests/search_tests.ts
tests/searchable_attributes_tests.ts
tests/settings_tests.ts
tests/stop_words_tests.ts
tests/synonyms_tests.ts
tests/typed_search_tests.ts
tests/unit_tests.ts
tests/update_tests.ts

This pr is pointing to the PR that fixes the issue #731 
In this PR we tests every route and sub-route used by this library to ensure there is no route that creates a double slash. 
It also tests the following cases
- http://localhost:7700// => should work and become http://localhost:7700/
- Every request made by meilisearch-js should not have a trailing slash
- http://localhost:7700/indexes/ ❌
- http://localhost:7700/indexes ✅
- Sub routes are not lost:  `http://localhost:7700/api/` + `indexes` should become `http://localhost:7700/api/indexes`

Add tests on each route to ensure avoiding double slashes

---

src/http-requests.ts
src/index.ts
src/meilisearch.ts
tests/attributes_for_faceting_tests.ts
tests/client_tests.ts
tests/displayed_attributes_tests.ts
tests/distinct_attribute_tests.ts
tests/documents_tests.ts
tests/dump_tests.ts
tests/index_tests.ts
tests/meilisearch-test-utils.ts
tests/ranking_rules_tests.ts
tests/search_tests.ts
tests/searchable_attributes_tests.ts
tests/settings_tests.ts
tests/stop_words_tests.ts
tests/synonyms_tests.ts
tests/typed_search_tests.ts
tests/unit_tests.ts
tests/update_tests.ts

In this PR is linked to #652. This issue raises the problem where the requested URL has a double slash. This does not impact the usability of meilisearch-js but could potentially become a problem. Also the error handler shows clearly the double slash when a communication error occurs. 
To avoid this problem in the future this PR does the following: 
- REFACTO: Removed all starting slashes on sub-routes in the code
- FIX: Add multiple check inside the http handler for the following cases: 
- If the pathname ends with a slash OR if the sub-route start with a slash, we do not add a slash
- If the pathname ends with a slash AND if the sub-routes start with a slash, we remove the starting slash in the sub route
- If the sub-routes ends with a slash, remove that slash for consistency  in URL …

Fix double slash error and refactor api routes

---

package.json
yarn.lock

Updated Jest that uses node-notifier. Version 8.0.0 of node-notifier introduced a injection risk by not checking the type an input.
Updated to latest jest fixes that issue.

Remove node-notifier vulnerability

---

jest.config.js
package.json
yarn.lock

This fixes the failing tests until this has changed https://github.com/jsdom/jsdom/issues/2961 
Tests were failing because of the latest version of `JSdom` that introduced this bug: https://github.com/jsdom/jsdom/issues/2961. We only have the bug now as we have updated jest to its latest version. 
Multiple solutions are considerable: 
- Adding a resolution to a previous version of jsdom which works with yarn but not npm
- Add a polyfill for globalThis
- Remove node 10 from test until resolved: https://github.com/loilo/livy/commit/83de8b1ab8110bd0986023903ccbf6e4b8ca9fd2
- Change the JsDom version used by explicitly telling so in jest config (which is kinda what `create-react-app` (85k stars) did but [without using an external library](https://github.com/facebook/create-react-app/pull/8955/ …

Temp fix for failing node v10

---

jest.config.js
package.json
yarn.lock

Usage of `jest-environment-jsdom` is not explicitly given anywhere I searched for it. But it appears it creates a jest environment that uses (depending on the version) a previous `jsdom`.
More information on my supposition here: https://github.com/facebook/jest/issues/11025
Npm package of jest-environment-jsdom with 10million downloads a week but no readme  https://www.npmjs.com/package/jest-environment-jsdom 🤯

Fix failing test by using an older version of jsdom

---

.code-samples.meilisearch.yaml
README.md
examples/node/search_example.js
examples/typescript-browser/package.json
examples/typescript-browser/src/index.ts
examples/typescript-browser/tsconfig.json
examples/typescript-browser/webpack.config.js
examples/typescript-node/src/index.ts
rollup.config.js
src/meilisearch.ts
src/types.ts
tests/env/esm/src/index.js
tests/env/esm/webpack.config.js
tests/env/express/public/index.html
tests/env/node/index.js
tests/env/typescript-node/src/index.ts
tests/index_tests.ts
tests/meilisearch-test-utils.ts
tsconfig.json

Fixes: #686
Based on: https://github.com/meilisearch/instant-meilisearch/issues/122
To showcase named exports a few changes have been made in README and code-samples: 
- Separate ES, CJS and browser syntax for clarity
- Changed code-samples the same way
**These changes in the readme and code samples are open for discussion.**
MeiliSearch Js decided to go in the direction of new best practices in JS libraries by changing from default export to named export.
ES:
```javascript
import { MeiliSearch } from 'meilisearch' // ES
import DefaultMeiliSearch  from 'meilisearch' // ES
// new MeiliSearch(..)
// new DefaultMeiliSearch.MeiliSearch(..)
``` 
Node
```javascript
const { MeiliSearch } = require('meilisearch') // Node
const DefaultMeiliSearch = require('meilisearch') // Node
// new …
```

Named exports

---

.code-samples.meilisearch.yaml
README.md
src/meilisearch.ts
src/types.ts
tests/index_tests.ts

**Description**
Checking that method `health()` return `{'status': 'available'}` and added `isHealthy()` method who return boolean value
**Issue related**
meilisearch/integration-guides#55
**Some points of concern**
- `health` method didn't return json but JSObject
- I define `Health` interface this way, which means API should return `'available'` and this could lead to more maintenance but but it felt cleaner to me
```js
export interface Health {
status: 'available'
}
```

Standardize health method

---

package.json

@curquiza's update: the minor is increased because of the Node.js 10 support removal.

Update to v0.19.0

---

tests/documents_tests.ts

Behavior changed when primary key is not inferable see: https://github.com/meilisearch/MeiliSearch/issues/1487

Resolve non inferable pk tests

---

.github/dependabot.yml
.github/workflows/tests.yml
.yamllint.yml

Yaml linter to avoid the following errors: https://github.com/meilisearch/meilisearch-go/issues/173
Example on error: 
```
Error: -samples.meilisearch.yaml:374:1: [error] syntax error: could not find expected ':' (syntax)
Error: ub/dependabot.yml:3:1: [error] wrong indentation: expected 2 but found 0 (indentation)
Error: ub/dependabot.yml:10:3: [error] wrong indentation: expected 4 but found 2 (indentation)
Error: ub/workflows/tests.yml:64:5: [error] wrong indentation: expected 6 but found 4 (indentation)
Error: Process completed with exit code 1.
```

Add lint tests for yaml files

---

src/lib/indexes.ts
src/types/types.ts
tests/env/typescript-node/src/index.ts

This level of type complexity was not maintainable and not exhaustive as it would require a lot of work to make it consistent around the whole codebase. 
It also made the usage of the library to limiting in projects that would want different degrees of severity

Remove unecessary type complexity on searchParameters

---

src/lib/indexes.ts
src/lib/meilisearch.ts

Udpate the static method params order for consistency as mentioned. Fixes #921

refactor(#921): Update the params order

---

src/lib/meilisearch.ts
src/lib/utils.ts
tests/client_tests.ts

- Addresses issue #784 
- The bug was caught in docker-compose as the user is putting the hostname which is resolved by docker dns and it allows hostname to be without protocol mentioned in it (https or http)
- This is because the javascript URL() constructor does not accept url which does not follow one of the standard url pattern, which can either be '<protocol>://<host>' or '<host>:<port>'
- To fix it, we can check presence of protocol at the beginning of host and append http by default if any protocol is not present.

Add http protocol at the beginning of the URL if not present

---

src/lib/http-requests.ts
src/lib/meilisearch.ts
src/lib/utils.ts
tests/client_tests.ts
tests/unit_tests.ts

the previous error was very unclear on what the problem was, in another repo I had to create a wrapper around the error. So I might just change it here: 
before: 
```
TypeError [ERR_INVALID_URL]: Invalid URL: http://
at onParseError (internal/url.js:259:9)
at new URL (internal/url.js:335:5)
// ....
input: 'http://',
code: 'ERR_INVALID_URL'
}
```
after: 
```
Error [MeiliSearchError]: The provided host is not valid.
at new HttpRequests (/meilisearch-js/dist/bundles/meilisearch.umd.js:320:17)
at new MeiliSearch (/meilisearch-js/dist/bundles/meilisearch.umd.js:2336:28)
// ....
type: 'MeiliSearchError'
}
```

Add a validator on the provided host

---

.code-samples.meilisearch.yaml

~I haven't tested this myself, so I'm not positive it's correct, but in the spec `'filter'` is always treated as a string in the `searchRules` object.~
I asked @curquiza and she told me that
```
example = {
frites: "miam"
}
```
and
```
example = {
"frites": "miam"
}
```
are treated as exactly the same by JavaScript. In this case the syntax without quotes would actually be preferred since the key is only a single word. It does make me wonder why `patient_medical_records` is in quotes in the same sample--might be inconsistent? But anyway, sorry to bother you and feel free to close this PR 😅

Make tenant token generation code sample consistent w/ spec

---

src/types/types.ts

To avoid having to duplicate twice some types related to the search parameters this improvement makes an union between all types that shares the same elements

Create union between search parameters types

---

tests/get_search_tests.ts
tests/search_tests.ts
tests/typed_search_tests.ts

As per the changes made in the cropping behavior (now per words see [this spec](https://github.com/meilisearch/specifications/blob/f5c6a8e183e22cc3b80d9a0251c411250f31674f/text/0118-search-api.md#3111-attributestocrop) tests needed to be fixed

Fix cropping tests

---

src/types/types.ts
tests/get_search_tests.ts
tests/search_tests.ts

As per https://github.com/meilisearch/meilisearch/issues/2214 new search parameters are introduced: 
- `highlightPreTag`
- `highlightPostTag`
- `cropMarker`

Add new search parameters highlightPreTag, highlightPostTag and cropMarker

---

CONTRIBUTING.md

Version in package.json should not be prefixed by a `v`

Fix version naming in beta release explaination

---

tests/typed_search_tests.ts

An unexpected change in the pre-release of Meilisearch made a test fail. 
Since of the latest RC this has been fixed and thus the tested on skiped
https://github.com/meilisearch/meilisearch/issues/2318

Unskip formatted tests failing due to unexpected meilisearch change

---

tests/settings_tests.ts
tests/typo_tolerance_tests.ts

The setting `minWordLengthForTypo` inside the `typoTolerance` setting was wrongly named. 
In this PR it is updated to the correct settings name: `minWordSizeForTypos`
https://github.com/meilisearch/meilisearch/pull/2326

Update wrong naming inside typotolerance setting

---

README.md
src/lib/indexes.ts
tests/documents_tests.ts
tests/meilisearch-test-utils.ts

Fixes #1187
In a typed environment, when using the `updateDocuments` method, you should be able to provide only some parts of the document that you want to update. 
Unfortunately, the typing was asking for the whole document. This PR changes the type to `partial`

Make updateDocuments accept partial documents in typing

---

src/lib/indexes.ts

This removes unnecessary ternary operators in the `searchGet` method

Use optional chaining instead of ternary operators in `searchGet` method

---

.github/dependabot.yml

Nodemon is a dev dependency that does not impact the code base or the builds

Remove nodemon from dependabot watched dependencies

---

package.json

This version makes this package compatible with Meilisearch v0.27.0 :tada:
Check out the changelog of [Meilisearch v0.27.0](https://github.com/meilisearch/meilisearch/releases/tag/v0.27.0) for more information on the changes.
Even if the minor version improved, this PR does not introduce a breaking-change! 
- Ensure nested field support #1192
- Add the typo tolerance setting #1197 
- Add `typoTolerance` parameter in the `Settings` type.
- Creation of: `index.getTypoTolerance`, `index.updateTypoTolerance`, `index.resetTypoTolerance`
- Add `highlightPreTag` & `highlightPostTag` & `cropMarker` #1196
* Make updateDocuments accept partial documents in typing (#1209) @bidoubiwa
Thanks again to @bidoubiwa and @mmachatschek! 🎉

Update version for the next release (meilisearch-js v0.25.1)

---

src/lib/indexes.ts

The JS doc return statement had a typo throwing errors on jsdoc checkers

Fix return statement in jsdoc comment

---

.github/dependabot.yml
jest.config.js
package.json
src/errors/http-error-handler.ts
src/errors/meilisearch-api-error.ts
src/errors/meilisearch-communication-error.ts
src/errors/meilisearch-error.ts
src/errors/meilisearch-timeout-error.ts
src/lib/http-requests.ts
src/types/types.ts
tests/client_tests.ts
tests/errors_tests.ts
tests/index_tests.ts
tsconfig.json
yarn.lock

`MeiliSearchApiError` were labelled as `MeilisearchCommunicationError` this PR fixes this issue.
It also removes the `type` field from other custom errors as it is not a standard field in Error in javascript. It also conflicts with the `type` field returned by an error in Meilisearch.
- `MeilisearchCommunicationError` 
- `MeiliSearchTimeOutError`
- `MeiliSearchError`
`MeiliSearchErrorBody` is renamed `MeiliSearchErrorInfo` for clarity.
It also remove the unnecessary interface `MeiliSearchErrorInterface` as interfaces are used to create new classes corresponding following an interface rule, but no other custom error is planned with this interface.
The interface used for a parameter of the custom error is replaced with the type `MeiliSearchErrorInfo`  used across the different types.

Rework the custom Meilisearch Errors

---

src/indexes.ts
src/types/types.ts
tests/search.test.ts
tests/typed_search.test.ts

Fixes: #1198 
closes: #1212
Currently when using the search method: 
```ts
index('xxx').search(query: string, options: SearchParams = {}, config?: Partial<Request>)
```
the `options` parameter complying to the SearchParams type does not accept the `q` parameter in typescript. Which has made a few user having to make a work-around annoying:
```js
const query = params.q
delete params.q
await index.client(query, params)
```
Initially having the `query` as a first parameter has been chosen to make a search without options more simple ([algolia does the same](https://www.algolia.com/doc/api-reference/api-methods/search/#examples)).
Nonetheless, the most common use case would use the second `options` parameter. 
In `not typescript` the user can add `q` to the searchParams. The `q` is …

Allow query in search options

---

.code-samples.meilisearch.yaml
README.md
src/clients/client.ts
src/indexes.ts
src/types/types.ts
tests/client.test.ts
tests/dump.test.ts
tests/utils/meilisearch-test-utils.ts

Related to:
issue: https://github.com/meilisearch/meilisearch/issues/2371
All the changes:
I removed the tests from `client.tests.ts` related to dumps as they were a duplicate of the ones present in `dumps.tests.ts`

Update dumps method v0.28

---

README.md
src/clients/client.ts
src/indexes.ts
src/task.ts
tests/wait_for_task.test.ts

Update the response of waitForTasks that was using the Result type to prepare for the consistent pagination system #1269

Update waitForTasks return format to not use resource result

---

src/types/types.ts

wrong name 'disabledOnAttributes' rename to correct name 'disableOnAttributes'
Fixes #1275 
- [✔] Does this PR fix an existing issue?
- [✔] Have you read the contributing guidelines?
- [✔] Have you made sure that the title is accurate and descriptive of the changes?

fix: TypoTolerance type has a wrong key name

---

README.md
src/clients/client.ts
src/indexes.ts
src/task.ts
src/types/types.ts
tests/documents.test.ts
tests/env/typescript-browser/src/index.ts
tests/env/typescript-node/src/index.ts
tests/index.test.ts
tests/keys.test.ts
tests/task.test.ts

Add pagination system on the following resources: `keys`, `indexes`, `documents`

Add pagination system on resources for v0.28.0

---

README.md
src/clients/client.ts

- `deleteKey` and `updateKey` are also able to be recognizable by either the `uid` or the `key`.

Add keys parameter in missing routes v0.28.x

---

.code-samples.meilisearch.yaml

- Add `limit` parameter: `limit=3`

Update indexes code-sample for v0.28.0

---

.code-samples.meilisearch.yaml

- Only update `name` and `description`: `"name": "Products/Reviews API key",
"description": "Manage documents: Products/Reviews API key"`
- Update to add `limit` parameter: `limit=3' ` 
- Replace key `key` with `uid`: `6062abda-a5aa-4414-ac91-ecd7944c0f8d`
- Replace key `key` with `uid`: `74c9c733-3368-4738-bbe5-1d18a5fecb37`
- Replace updating `indexes` with `description`:  `{ "description": "Default Search API Key" }'`
- Replace key `key` with `uid`: `ac5cd97d-5a4b-4226-a868-2d0eb6d197ab
A part:

Update keys code-sample for v0.28.0

---

.code-samples.meilisearch.yaml

- Remove getting task from `movies` index
- filter tasks by `indexUid=movies`
- filter tasks by `status=succeeded,failed&type=documentAdditionOrUpdate`
- paginate tasks by `limit=2&from=10`
- paginate tasks by `limit=2&from=8`

Update task code samples v0.28.0

---

.code-samples.meilisearch.yaml

- Rename code sample to `search_parameter_guide_show_matches_position_1`
- Rename `matches` parameter to `showMatchesPosition` 
- Rename code sample to `faceted_search_facets_1`
- Rename `facetsDistribution` parameter to `facets`

Update search code-sample for v0.28.0

---

.code-samples.meilisearch.yaml

- ~Add  `get_pagination_settings_1` [PR](https://github.com/meilisearch/documentation/pull/1759)~
- for the `books` index
- for the `books` index
- Update `"maxTotalHits": 100`
- ~Add  `reset_pagination_settings_1` [PR](https://github.com/meilisearch/documentation/pull/1759)~
- for the `books` index
- add ` "pagination": {"maxTotalHits": 5000}` 
- add `"faceting": { "maxValuesPerFacet": 200}` 
- ~Add `get_faceting_settings_1` [PR](https://github.com/meilisearch/documentation/pull/1761)~
- for the `books` index 
- for the `books` index 
- Update: `"maxValuesPerFacet": 2`
- ~Add `reset_faceting_settings_1` [PR](https://github.com/meilisearch/documentation/pull/1761)~
- for the `books` index 
- for the `movies` …

Update settings code-sample for v0.28.0

---

src/indexes.ts
src/types/types.ts
tests/documents.test.ts

Related to [this issue](https://github.com/meilisearch/integration-guides/issues/205)
- GET /documents/:uid, GET /documents Add the possibility to reduce the body payload by using a query parameter called fields (previously called attributesToRetrieve), check the issue and the spec for the entire behavior.
Previous 
```js
function getDocument(docId: number)
```
new
```js
function getDocument(docId: number, parameters: DocumentQuery)
```
usage
```js
index.getDocument(1, { fields: ['title'] })
```

Add fields parameter to getDocument route for v0.28.0

---

.code-samples.meilisearch.yaml

- Add `fields` parameter: `fields=id,title,poster,release_date`

Update documents code-sample for v0.28.0

---

tests/index.test.ts
tests/keys.test.ts
tests/token.test.ts

Some tests were failing sometimes because of a bad handling on awaiting tasks and clearing the indexes

Fix tests failing because of bad task handling

---

.github/scripts/check-tag-format.sh
.github/workflows/publish.yml
CONTRIBUTING.md

To be able to create beta releases on different subjects: `bumps`, `features`, etc.. we needed to provide a better suited CI.
This CI also checks if the tag well formated to ensure we do not publish a version that does not follow the naming convention.
The workflow has been tested on a private directory and seems to work correctly
⚠️ the `--dry-run` tag on the beta `npm publish . --tag beta --dry-run` is voluntarily added. The idea is to make a try run to ensure that it does what it is suppose to do!

Create new publish CI for beta versions

---

.github/workflows/publish.yml

Test have been succesfull and we can now safely publish a beta to npm

Remove dry-run from beta npm publish

---

.code-samples.meilisearch.yaml

The code-sample is not up to date with the newly required code-samples. It had still the previous one
https://docs.meilisearch.com/learn/security/tenant_tokens.html#what-is-multitenancy

Fix tenant_token_guide_generate_sdk_1 code sample

---

.github/workflows/beta-tests.yml
.github/workflows/pre-release-tests.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
CONTRIBUTING.md
README.md
bors.toml
tests/env/esm/package.json
tests/env/esm/yarn.lock

Node 18 is already the default version the user gets whenever they download node. We must ensure we are compatible with this version
I forced the tests on all CI's and they were successful. I put back the condition to not run it now. 
Proof that they work: 
⚠️ TODO 
Updates are based on [instant-meilisearch CI's](https://github.com/meilisearch/instant-meilisearch/tree/main/.github)

Update CI's dependencies/consistency/ node 18 support

---

src/types/types.ts
tests/search.test.ts

Related to:
- issue: https://github.com/meilisearch/meilisearch/issues/2578
This improvement motivation is about letting the user customize the behavior of Meilisearch when retrieving documents according to the query words.
- Add a `matchingStrategy` parameter to search requests `search` and `searchRaw`. 
- The value `last` is the default strategy if the field is not specified.
- This field can receive only two valid options `last` or `all`.
Usage: 
Typescript
```js
index.search('hello world', { matchingStrategy: MatchingStrategies.ALL }) // default LAST
```
JavaScript
```js
index.search('hello world', { matchingStrategy: 'all' }) // default 'last'
```
- New search query parameter `matchingStrategy` #1324

Update search params for v0.29.0

---

.github/workflows/beta-tests.yml

The order made that the second condition was overriding the first one. Making the tests run anyway on bump beta;s

Change order of branches conditions in beta CI

---

src/types/types.ts
tests/keys.test.ts
tests/search.test.ts

Related to:
- issue: https://github.com/meilisearch/meilisearch/issues/2578
This change enables the creation of keys with only one string as `action` that represents all the actions for a resource, e.g. `indexes.*` can do everything related to `indexes`.
- Add or replace some `test` cases to use this new compressed version.
- `actions` field during `key` creation now accepts wildcards on actions. For example: `indexes.*` provides rights to create/get/delete/update indexes.

Add tests on keys action for v0.29.1

---

.code-samples.meilisearch.yaml

Wrong json document import in the getting started code sample. From `../small_movies.json` to `./movies.json`

Fix getting started code-sample json import

---

src/clients/client.ts
src/indexes.ts
src/task.ts
src/types/types.ts
tests/keys.test.ts
tests/task.test.ts

I have updated the codebase so that the keys which are technically of date type are constructed with `Date()` object before returning.
Also I have updated the Test cases.
Fixes #1223 

refactor: Construct date type for related keys

---

.code-samples.meilisearch.yaml
README.md
src/indexes.ts
tests/faceting.test.ts
tests/settings.test.ts

Add faceting index settings methods

---

.code-samples.meilisearch.yaml
README.md
src/indexes.ts
tests/pagination.test.ts
tests/settings.test.ts

Add support to the pagination setting customization at the index level

---

tests/client.test.ts
tests/displayed_attributes.test.ts
tests/distinct_attribute.test.ts
tests/documents.test.ts
tests/dump.test.ts
tests/faceting.test.ts
tests/filterable_attributes.test.ts
tests/get_search.test.ts
tests/index.test.ts
tests/keys.test.ts
tests/pagination.test.ts
tests/ranking_rules.test.ts
tests/search.test.ts
tests/searchable_attributes.test.ts
tests/settings.test.ts
tests/sortable_attributes.test.ts
tests/stop_words.test.ts
tests/synonyms.test.ts
tests/task.test.ts
tests/token.test.ts
tests/typed_search.test.ts
tests/typo_tolerance.test.ts
tests/utils/meilisearch-test-utils.ts
tests/wait_for_task.test.ts

Standardise naming convention of Private and Public keys in test to Admin and Seach respectively
Fixes #1137 
-Standardises the naming convention of Index and Admin Keys in the tests by updating the remaining Private and Public string constants been passed. 

Standardise naming convention of Private and Public keys in test to Admin and Search respectively. 

---

src/index.ts

As per #1343 Task and EnqueuedTask became classes but are not exported publically.  See issue #1373 
In this PR, the new classes Task and EnqueuedTask are exported and importable by users of the package

Export Task and EnqueuedTask

---

src/types/types.ts
tests/get_search.test.ts
tests/search.test.ts
tests/typed_search.test.ts

Adds the new page selection component 
TODO: 
Response: 
Tests

Add pagination feature for v0.30.0

---

src/http-requests.ts
src/task.ts
src/types/types.ts
tests/get_search.test.ts
tests/search.test.ts
tests/task.test.ts
tests/typed_search.test.ts

Add new filters on the `get /tasks` route.
Present in this [spec](https://github.com/meilisearch/specifications/pull/195)
TODO: 
V0.30.0rc1
- TasksQuery: 
- Errors: 
V0.30.0rc0
in TasksQuery:
in `errors`:
Tests:

Add tasks filters for v0.30

---

src/types/types.ts
tests/get_search.test.ts
tests/search.test.ts
tests/task.test.ts
tests/typed_search.test.ts

The `error` field in Task is now always present and has either an error or is equal to null

Add default value of error field in task to null for v0.30.0

---

src/task.ts
src/types/types.ts

- issue: https://github.com/meilisearch/meilisearch/issues/2582
- spec: https://github.com/meilisearch/specifications/pull/162

Remove batch uid for v0.30.0

---

.code-samples.meilisearch.yaml
src/indexes.ts
src/types/types.ts
tests/task.test.ts

V0.30.0rc1
- TasksQuery: 
- Task details:

Rename some task filter to their plural form for v0.30.0

---

src/types/types.ts
tests/task.test.ts

As per [this issue](https://github.com/meilisearch/meilisearch/pull/3080)
- `originalFilters` introduced in #1376 is renamed to `originalFilter`
⚠️ Tests are failing because of #1401

Rename setting detail original filters to original filter for v0.30.0

---

src/types/types.ts

Fixes #1381
Make all the fields of details field of TaskObject optional

Make all the fields of details field of TaskObject optional

---

src/types/types.ts
tests/documents.test.ts

As per [this issue](https://github.com/meilisearch/meilisearch/pull/3081)
- `matched_documents` introduced here #1386 is renamed to `providedIds`

Add setting detail providedIds for v0.30.0

---

src/indexes.ts
tests/env/typescript-node/src/index.ts
tests/search.test.ts
tests/typed_search.test.ts

No
This pr fix the default genetic type params of `search` and `searchGet`, it should use generic type param of `index`
expected type behavior in readme
```ts
client.index<T>('xxx').search(...): Promise<SearchResponse<T>>
```
current actually type, because `search` has a default generic type param `Record<string, any>`:
```ts
client.index<T>('xxx').search(...):
```
is implicit 
```ts
client.index<T>('xxx').search<Record<string, any>>(...):
```
and it's actually
```ts
client.index<T>('xxx').search(...): Promise<SearchResponse<Record<string, any>>>
```

types: fix search default type of `search` and `searchGet`

---

src/indexes.ts
src/types/types.ts

Fixes https://github.com/meilisearch/meilisearch-js/issues/1421
remove `Document` and `Documents`

remove `Document` and `Documents`

---

tests/documents.test.ts

To ensure primary key are infered correctly, some tests are added.
See [spec](https://github.com/meilisearch/specifications/pull/208)

Add tests on primary key inference for v1.0.0 of Meilisearch

---

src/types/types.ts
tests/client.test.ts
tests/task.test.ts

See [specification](https://github.com/meilisearch/specifications/pull/212)

Update error codes for Meilisearch v1.0.0

---

package.json
src/package-version.ts

This version makes this package compatible with Meilisearch v1.0.0 :tada:
Check out the changelog of [Meilisearch v1.0.0](https://github.com/meilisearch/meilisearch/releases/tag/v1.0.0) for more information on the changes.
- Some error codes were added #1438 
- Some error codes were removed #1438

Update version for the next release (v0.31.0)

---

package.json
src/package-version.ts

This repository was not up to date with the latest typescript, causing a typing error in environments with a more recent typescript version

Update version for the next release (v0.31.1)

---

.github/scripts/beta-docker-version.sh
.github/scripts/check-tag-format.sh
.github/workflows/meilisearch-prototype-tests.yml
.github/workflows/pre-release-tests.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
CONTRIBUTING.md

Based on this: https://github.com/meilisearch/instant-meilisearch/pull/898/files
It introduces consistency in the beta naming branches and ensures that the release works as expected.

Improve beta release process

---

.github/scripts/prototype-docker-version.sh

Script was failing because of a variable named incorrectly

Fix wrong naming in docker prototype script

---

src/indexes.ts
src/types/types.ts
tests/search.test.ts

Fixes #1434
As described in #1434 with this PR the type of `SearchResponse` is determined by the params used for the search.

Make `SearchResponse` types more strict regarding to pagination

---

README.md
src/clients/client.ts
src/types/types.ts
tests/search.test.ts

Introduces the `client.multiSearch()` method as per the [specifications](https://github.com/meilisearch/specifications/pull/225)
SDK requirements: https://github.com/meilisearch/integration-guides/issues/251

Add multi search method of Meilisearch v1.1

---

.github/workflows/pre-release-tests.yml

When a push occurs on a branch pointing to a bump branch, the push action does not trigger as it does not match the required branch patterns. When a pull_request activity on a bump branch occurs, the pre-release tests were triggered but because of the wrong if condition, the jobs were not executed.
The if condition should ensure that the base branch corresponds to the pull_request branch patterns.
Which is now the case

Fix pre-release CI not triggering

---

tests/env/express/package.json
tests/env/express/yarn.lock

Outdated puppeteer versions led to throws in new MacOS venture env

Update puppeteer versions

---

package.json

Its not clear that the browser tests is using the build of the project and not the up to date source files.
To ensure we avoid running the test on outdated builds, this PR adds `yarn build` before the tests are ran

Add building of the project before running the browser tests

---

README.md
src/clients/browser-client.ts
src/http-requests.ts
src/types/types.ts
tests/client.test.ts

feat: added support for custom http client
- adds support for usages with preconfigured http clients like axios for using ms through a proxy for example
```
const client: MeiliSearch = new MeiliSearch({
host: 'http://localhost:3000/api/v0/meilisearch/proxy',
httpClient: async (url, opts) => {
const response = await $charles.http!.getClient().request({
url,
data: opts?.body,
headers: opts?.headers
})
return response.data
}
})
```
- adds support for customizing the requests created by `httpRequests` 
- removes `headers` config param and introduces `requestConfig` instead which can be used to customize all fetch config

feat: added support for custom request config

---

src/types/types.ts
tests/search.test.ts

If a facetStat for a given facet is present, it will always contain min and max.

Remove min max being optional in facetStats results

---

README.md
src/http-requests.ts
src/indexes.ts
src/types/types.ts
tests/raw_document.test.ts

Partial: #1061 
Introduces two methods on Index(): 
- `addDocumentsFromString`
- `updateDocumentsFromString` 
These allow the user to add documents using any of the following format: `csv`, `json` or `jsonld`.
They require 2 parameters and 1 optional parameter:
- the documents in a string
- the content type, either one of the following options:
-  `'text/csv'` or `ContentType.CSV` in typescript
- `'application/x-ndjson'` or `ContentType.NDJSON` in typescript
- 'application/json' or `ContentType.JSON` in typescript
- The document addition options. for example the primary key
The content of the string must match its content-type. Only when using the `CSV` format it is possible to use `csvDelimiter`
Usage:
```ts
client.index('myIndex').addDocumentsFromString(documents: string, contentType: …
```

Add method to add/update documents from a string

---

src/clients/client.ts

Fixes #1478
Remove the extra slash in the URL segment for multi-search which prevents the host configuration's path being used.

Fix multiSearch to allow using host config with path

---

src/types/types.ts

`PUT` is not a value of `ContentType` and should not be part of it

remove PUT on contentType enum

---

.code-samples.meilisearch.yaml

`client.stats()` isn't a function according to the latest version of `meilisearch-js`, so I went ahead and corrected the documentation for [here](https://www.meilisearch.com/docs/reference/api/stats#stats-object).
As `client.getStats()` is correct function that should be displayed.
Corrects documentation's recommended function, as that function doesn't exist within the new release, its `getStats()` vs the incorrect function that is `stats()`

client.stats() isn't a function in the latest release, it seems `client.getStats()` is the correct function.

---

package.json
src/errors/meilisearch-communication-error.ts
src/http-requests.ts
tests/env/node/getting_started.js

Fixes #1487 
Load `cross-fetch/polyfill` only if `fetch` is `undefined`.

Add conditional loading for cross-fetch/polyfill - favour native fetch

---

.eslintrc.js
package.json
yarn.lock

Fixes #1423 
- Uninstall the `eslint-plugin-jsdoc` dependency.
- Remove all the jsdoc eslint rules from the `.eslintrc.js` file.

Remove the `jsdoc` eslint plugin

---

src/indexes.ts

getTypoTolerance function should return type "TypoTolerance" rather than string array.
- replace getTypoTolerance return value type with "TypoTolerance"

fix(type): getTypoTolerance return value type

---

tsconfig.json

By default, the target in a tsconfig is `ES3`. This ensures compatibility with environments that predates 2015. The downside of having this insurance is the size of the bundle.
By changing from `ES3` to `esnext` we go from a bundle size of 108k to a bundle size of 60k.
Looking at what other libraries do, they seem to agree on using `esnext` as a target. While you might argue that it raises some risks, our library, like the other ones using `esnext`, is made to be used in modern environments.

Change target in tsconfig to ES6

---

src/types/types.ts
tests/__snapshots__/faceting.test.ts.snap
tests/__snapshots__/settings.test.ts.snap
tests/faceting.test.ts
tests/settings.test.ts

issue: https://github.com/meilisearch/meilisearch/issues/3612
discussion: https://github.com/meilisearch/product/discussions/519#discussioncomment-6030480
Adds the ability to sort facets by their value which could be by using alphanumerical or count.
Ensure the SDKs can handle the new search parameter sortFacetValuesBy. This enum can only take count or alphanumeric.
- Adds the `sortFacetValuesBy` setting in `Settings['faceting']`

Add sort order for facet values for Meilisearch v1.3

---

src/indexes.ts
src/types/types.ts
tests/__snapshots__/get_search.test.ts.snap
tests/__snapshots__/search.test.ts.snap
tests/get_search.test.ts
tests/search.test.ts

issue: https://github.com/meilisearch/meilisearch/issues/3772
spec: Define fields to search on at runtime  [specifications#251](https://github.com/meilisearch/specifications/pull/251)
- Add support for receiving a new key, attributesToSearchOn (which is an array of field names), that will enable running searches over a subset of searchableAttributes without modifying Meilisearch’s index settings.

Add attributes to search on for Meilisearch v1.3

---

README.md
package.json
src/indexes.ts
src/package-version.ts
src/types/types.ts
tests/facet_search.test.ts

A new method `index.searchForFacetvalue` method is introduced.
See explanation on this [method here](https://github.com/meilisearch/product/discussions/515#discussioncomment-5806759).
[related PR](https://github.com/meilisearch/meilisearch/pull/3699)
Usage example:
```js
await client.index(index.uid).searchForFacetValue({
facetQuery: 'act',
facetName: 'genres',
})
```

Add the searchForFacetValues method for Meilisearch v1.3.0

---

src/types/types.ts

Fixes #1567
Meilisearch tasks type can be `dumpCreation` but it's missing in the type `TaskTypes` in `meilisearch-js`.
See tasks documentation here: https://www.meilisearch.com/docs/reference/api/tasks#type
-  Add `dumpCreation` in type `TaskTypes`
- Reorder in alphabetical order

fix: add `dumpCreation` in type `TaskTypes`

---

.github/dependabot.yml

To avoid being spammed with none-critical dependencies updates suggested by dependabot, we are changing from `ignore` to `allow` in the dependabot file. Ensuring we only update the critical dependencies.
```
- dependency-name: cross-fetch
```
cross-fetch is kept as it is the only one that is builded with the package. Updates of this library ensure that the library is kept up to date with new versions of `node`.

Update dependabot changing ignore list to allow list

---

.prettierignore
README.md
package.json
src/indexes.ts
src/package-version.ts
src/types/types.ts
tests/__snapshots__/settings.test.ts.snap
tests/dictionary.test.ts
tests/non_separator_tokens.test.ts
tests/separator_tokens.test.ts
tests/settings.test.ts

Fixes #1555
Fixes #1556
- Modify the indexes file accordingly
- Create tests
- Add Dictionary type
- Modify the indexes file accordingly
- Create tests
- Add Dictionary type

prototype-beta: Tokenizer customization

---

.code-samples.meilisearch.yaml

I created [scripts to manage code samples](https://github.com/meilisearch/integration-automations/pull/164) (internal only)
I found out the following code samples are still in this repo but not used by the documentation anymore:
```bash
meilisearch-js
- 'documents_guide_add_movie_1' not found in documentation
- 'getting_started_communicating_with_a_protected_instance' not found in documentation
- 'faceted_search_facets_1' not found in documentation
- 'faceted_search_2' not found in documentation
```
And the missing code samples
```
meilisearch-js
- 'getting_started_typo_tolerance' not found
```
I also changed some `"` into `'`

Fix code samples (remove useless, and add missing)

---

src/task.ts
src/types/types.ts

Fixes #1588
`const enum` is not really suited for libraries (ref https://youtu.be/jjMbPt_H3RQ?feature=shared&t=249 and https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls) and cause issues in typescript projects with `isolatedModules: true` (like Next.js). Instead, regular objects can be used (like done in https://github.com/meilisearch/meilisearch-js/issues/1350) with `as const` to make them type safe. 
About the `as readonly string[]` in cfcda4fb0879370d8a6280d930136a34527b7aaf, this could probably have been solved by a type guard as well, but I opted for the type cast option instead to avoid runtime code changes. 

Fix const enum issues

---

src/browser.ts
src/index.ts

Fixes #1600
Add export for `MeiliSearch` class with the identifier `Meilisearch`

feat: add export for MeiliSearch as Meilisearch

---

src/errors/meilisearch-api-error.ts
src/errors/meilisearch-communication-error.ts
src/errors/meilisearch-timeout-error.ts

Fixes #1565 
- Ensure that the base error class(MeiliSearchError) inherits the standard error.
- All other error classes inherit the MeiliSearchError.

Update error inheritance to extend `MeiliSearchError`

---

tests/errors.test.ts

Fixes #1608
Fixes the test name in `error.test.ts` to accurately reflect the tested functionality.

Fix test name in error.test.ts

---

README.md
src/indexes.ts
src/types/types.ts
tests/__snapshots__/settings.test.ts.snap
tests/proximity_precision.test.ts
tests/settings.test.ts

Introduction of the proximity precision settings:
- addition of the new functions (add / update / delete)
- update the readme (addition of the new `proximity precision` section + addition of missing links)
- update types
- addition of new tests
- update snapshots
⚠️ Note that the snapshot will need to be updated again to accept the new `embedders` object (will come in a specific PR dedicated to the vector search)

feat: add proximity precision settings

---

README.md
src/indexes.ts
src/types/types.ts
tests/__snapshots__/settings.test.ts.snap
tests/embedders.test.ts
tests/get_search.test.ts
tests/search.test.ts

- Addition of new sub-routes for settings: embedders
- Update of the Readme
- Update types
- Update snapshots
- Add tests for embedders sub-routes
- Update tests for both get and post search

Implement vector search experimental feature

---

tests/__snapshots__/settings.test.ts.snap

Update snapshots which were failing after `embedders` were removed from the settings by default

fix: snapshots after removing embedders from default settings

---

src/types/types.ts

Fixes #<issue_number>
- Enables limit and offset according to documentation: https://www.meilisearch.com/docs/reference/api/documents

Enable limit and offset according to documentation.

---

package.json
scripts/build.js
scripts/file-size.js
src/http-requests.ts
src/indexes.ts
src/task.ts
src/types/types.ts
src/utils.ts
tests/utils/meilisearch-test-utils.ts

This PR should be merged right after the https://github.com/meilisearch/meilisearch-js/pull/1616

Fix code style after configuration changes

---

src/indexes.ts
src/types/types.ts
tests/searchCutoffMs.ts

Fixes #1639 
- Add the **SearchCutoffMsSetting** type to **Settings**
- Add new methods `getSearchCutoffMs()`, `updateSearchCutoffMs()` and `resetSearchCutoffMs()` to **Index** class
- Add the tests for the newly added API

Add searchCutoffMs index setting

---

src/types/types.ts

Fixes #1637 
- Add `null` type to **Embedder**

Add null to Embedder type

---

src/types/types.ts
tests/__snapshots__/settings.test.ts.snap
tests/embedders.test.ts
tests/get_search.test.ts
tests/search.test.ts
tests/settings.test.ts

Fixes #1641
- Removal of the `vector` and `_semanticScore` fields from the SearchResponse
- Addition of a new `distribution` field to all embedders
- Addition of 2 new embedders: `REST` and `Ollama`
- Update failing tests & snapshots
- Addition of tests + missing tests
⚠️ **CI failing**
CI fails because of 2 things:
- The `distribution` field is not retrieved correctly on the `settings/embedders` routes (see https://github.com/meilisearch/meilisearch/issues/4594)
- The Ollama embedder isn't retrieved completely (see https://github.com/meilisearch/meilisearch/issues/4595 )
Once those 2 things are fixed, it should be fine 🙌

feat: hybrid search improvements for v1.8.x

---

README.md

Update some links to the documentation (URL was wrong or not existing)

Update readme links to the documentation

---

.code-samples.meilisearch.yaml
docker-compose.yml
src/clients/client.ts
src/clients/node-client.ts
src/token.ts
tests/token.test.ts

After the introduction of this PR https://github.com/meilisearch/meilisearch-js/pull/1616 we had a bunch of issues related to vite configuration on client projects as shown here https://github.com/meilisearch/meilisearch-js-plugins/issues/1299
This PR introduces the rollback needed to fix the consumer's code. If this change is not enough, I will completely reverse the PR 1616.
Edit:
I was able to solve the issue, by using this branch with this [reproduction repo](https://github.com/flexchar/meili-issue-1299) I could build the project and also run the application without any issue.
But this change introduces some breaking changes in the JWT code:
Now it is required to use await: `await client.generateTenantToken(..)` instead of just `client.generateTenantToken(..)`.

Update crypto statement to fix vite issue

---

.eslintrc.js
.prettierrc.js
tsconfig.eslint.json
tsconfig.json

In #1616 I updated configurations, and left a bunch of explanatory comments that should've been viewed and removed. Maybe this approach wasn't the best, and should've instead commented on the PR, but anyways, lets remove them, they shouldn't have ended up in main branch.

Remove unneeded comments from config files

---

src/types/types.ts
tests/search.test.ts

Fixes #1666 
- Add frequency matching strategy

Add frequency matching strategy

---

src/types/types.ts
tests/search.test.ts

Fixes #1665
- Add rankingScoreThreshold in search

Add rankingScoreThreshold in search

---

src/types/types.ts
tests/get_search.test.ts

Related to https://github.com/meilisearch/meilisearch-js/issues/1665
- Add `rankingScoreThreshold` to `searchGet` + add related test

feat: add `rankingScoreThreshold` to `searchGet`

---

src/indexes.ts
src/types/types.ts
tests/embedders.test.ts

Fixes #1667
- Addition of a new `searchSimilarDocuments` function
- Addition of the related test

feat: get similar documents

---

src/types/types.ts
tests/documents.test.ts
tests/get_search.test.ts
tests/search.test.ts

Fixes #1675
- Addition of `retrieveVectors` for search (POST and GET)
- Addition of `retrieveVectors` for documents query (POST and GET)
- Add related tests

feat: hybrid search changes

---

package.json
rollup.config.js
scripts/build.js
scripts/file-size.js
src/token.ts
tests/env/esm/webpack.config.js
tests/env/nitro-app/tests/client.test.js
tests/env/typescript-browser/webpack.config.js
tests/token.test.ts
yarn.lock

I am aiming to slowly try to update and simplify this repository, and maybe learn a thing or two along the way.
- add `"exports"` field to `package.json`
- It is the new way of defining your exported files, instead of just relying on one single [`"main"`](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#main) export for Node.js
- This way Node.js can conditionally determine which exported file to import based on the fact that `require` or `import` was used, previously Node.js even in ESM mode always imported the commonjs version of this package, but now it can import the ESM version
- https://webpack.js.org/guides/package-exports/
- [subpath-exports](https://nodejs.org/docs/latest-v20.x/api/packages.html#subpath-exports)
- …

Add `package.json` `"exports"` field

---

package.json
rollup.config.js

Fix package exports

---

src/types/types.ts
tests/__snapshots__/settings.test.ts.snap
tests/embedders.test.ts
tests/get_search.test.ts
tests/search.test.ts

Fixes #1714
- Moved the AI-search-related tests to the `embedders` test file for easier maintenance
- Adapt types related to AI-search:
- `embedder` is now mandatory for GET and POST searches
-  Addition of `documentTemplateMaxBytes` (except for userProvided embedders)
- Addition of `binaryQuantized`
- Update snapshots (`documentTemplate` has been updated)
- Update tests

feat: AI-powered search changes for v1.11

---

src/types/types.ts
tests/search.test.ts

Fixes #1713
- Addition of the `facetsByIndex` field on multi-search requests
- Addition of the `mergeFacets` field on multi-search requests
- Addition of new tests
- Rename the indexUid of the test dataset from "movies_test" to "books" since we're sending books (no effet on the tests)

feat: support facet distribution for federated search

---

eslint.config.js
tests/client.test.ts
tests/dictionary.test.ts
tests/displayed_attributes.test.ts
tests/distinct_attribute.test.ts
tests/documents.test.ts
tests/dump.test.ts
tests/embedders.test.ts
tests/faceting.test.ts
tests/filterable_attributes.test.ts
tests/get_search.test.ts
tests/index.test.ts
tests/localized_attributes.test.ts
tests/non_separator_tokens.test.ts
tests/pagination.test.ts
tests/proximity_precision.test.ts
tests/ranking_rules.test.ts
tests/search.test.ts
tests/search_cutoff_ms.test.ts
tests/searchable_attributes.test.ts
tests/separator_tokens.test.ts
tests/settings.test.ts
tests/snapshots.test.ts
tests/sortable_attributes.test.ts
tests/stop_words.test.ts
tests/synonyms.test.ts
tests/task.test.ts
tests/token.test.ts
tests/typed_search.test.ts
tests/typo_tolerance.test.ts

Fixes #1745
- Removed the vitest exceptions from the eslint config and addapted the tests accordingly

Remove eslint vitest exceptions

---

.github/workflows/tests.yml

Fixes #1750
- Use the `latest` in the CI for testing instead of forcing the usage of the v1.11

fix: pull the latest in the CI instead of forcing the v1.11

---

CONTRIBUTING.md

with the minimum version of node required
Hey, I tried to run the test and encountered multiple errors coming from our outdated `CONTRIBUTING.md`.
It says the minimum version of node supported is the v14, but when I tried it gave me this error:
Then I tried the v15 and it gave me this error:
Finally, the v16 worked, so the range of accepted version should be v16 to v18.
-----
Then I tried to run the tests, which doesn't work anymore because apparently we now requires the installation of vitest

Update CONTRIBUTING.md with minimal Node version

---

src/types/types.ts
tests/__snapshots__/get_search.test.ts.snap
tests/__snapshots__/search.test.ts.snap
tests/get_search.test.ts
tests/search.test.ts
tests/typed_search.test.ts

Fixes #1772 
- Updates the dataset used in tests so `genre` is an array
- Updates the tests to still work after making `genre` an array
- Uses the new `genre` array to test that `_matchesPosition` return the correct value when matching against arrays

Add indices to matches position

---

src/types/types.ts
tests/__snapshots__/settings.test.ts.snap
tests/task.test.ts

Fixes #1769 
- Add `reverse` to `TasksQuery` type
- Add test to ensure it's working

Add reverse parameter for getTasks

---

README.md
src/indexes.ts
src/types/types.ts
tests/__snapshots__/facet_search_settings.test.ts.snap
tests/__snapshots__/prefix_search_settings.test.ts.snap
tests/__snapshots__/settings.test.ts.snap
tests/facet_search_settings.test.ts
tests/prefix_search_settings.test.ts
tests/settings.test.ts

Fixes #1770 
- Update `Settings` type so the methods getSettings(), and updateSettings can accept the new settings fields: facetSearch & prefixSearch
- Add the methods for facet search settings:  `getFacetSearch()`, `updateFacetSearch()`, and `resetFacetSearch()` 
- Add the new methods for prefix search settings: `getPrefixSearch()`, `updatePrefixSearch()`, and `resetPrefixSearch()` calling the appropriate Meilisearch routes
- Add the necessary tests (I took example on the tests for displayed attributes settings)
- Update the README

Add new `prefixSearch` and `facetSearch` index settings

---

src/batch.ts
src/types/types.ts
tests/batch.test.ts

Fixes #1798
- Add types for the `progress` field
- Add `progress` in the BatchObject returned by the client

Add batch progress

---

nodemon.json
package.json
yarn.lock

Previously `nodemon` was used for TypeScript watch mode, but TypeScript now supports watch mode by itself. For this reason we no longer require `nodemon`.

Remove `nodemon` dependency

---

package.json

Fixes issue that results in the following type error for when [module](https://www.typescriptlang.org/tsconfig/#module) is set to `"node"` or other older version:

Add types field for backwards compatibility in package.json

---

vite.config.js

- adjust footer applied by Vite, so that it doesn't cause issues with Node.js, and doesn't apply default export to global variable

Fix Vite global patch for browser environments

---

.github/workflows/meilisearch-prototype-tests.yml
.github/workflows/pre-release-tests.yml
.github/workflows/publish.yml
.github/workflows/tests.yml
CONTRIBUTING.md
README.md
bors.toml

- adds latest Node.js major LTS version to the test matrix (https://github.com/nodejs/Release)

Test latest major Node.js LTS version

---

README.md

Fixes #1843
- refactors `README.md` installation and import sections

Refactor `README.md` installation and import sections

---

src/types.ts
tests/index.test.ts

Fixes #1875 
adds the documents database metrics to `indexStats` type.

Add documents database metrics to indexStats type

---

src/types.ts
tests/client.test.ts

Fixes #1873 
Adds usedDatabaseSize metric to `Stats` type.

Add usedDatabaseSize field to stats type

---

src/meilisearch.ts
src/types.ts
tests/client.test.ts
tests/search.test.ts

Fixes #1872
Implement the experimental feature for [remote federated search requests](https://www.meilisearch.com/docs/learn/multi_search/implement_sharding?utm_campaign=oss&utm_source=github).

Implement the experimental feature for remote federated search requests.

---

package.json

- fixes `"repository"` field according to https://docs.npmjs.com/cli/v9/configuring-npm/package-json#repository

Fix `package.json` `"repository"` field

---

.github/workflows/meilisearch-prototype-tests.yml
.github/workflows/pre-release-tests.yml
.github/workflows/tests.yml

Trace Node.js warnings in CI tests
