meilisearch/meilisearch-js

package.json, yarn.lock
update node minimum version in dependencies to match required version of circle-ci
=> build: update node minimum

yarn.lock
=> build: upgrade dependencies

.circleci/config.yml
=> ci: update circle ci image to chakracore-10.13

.circleci/config.yml
=> ci: update node image to 10.10

README.md
=> style: update ci badge on readme

README.md
=> style: add dependabot badge

.circleci/config.yml
=> ci: update ci image to 12.11

src/__tests__/meili.ts, src/index.ts
Updating Health route calls and tests.
=> Health route changed and added tests

src/__tests__/indexes.ts, src/__tests__/meili.ts, src/index.ts
Cleaning of tests and adding new ones
=> Changes to health route

src/__tests__/meili.ts
=> Meili objects tests

examples/small_movies.json, src/__tests__/indexes.ts, src/__tests__/meili.ts, src/indexes.ts
All indexes routes finished and tested.
Plus added a small movie dataset for quicker testing.
=> All indexes routes and tests

README.md, examples/search_example.js, src/__tests__/indexes.ts
This PR provides extensive search tests to test if the js client handles the query parameters correctly.
Additionally, a search example is provided in the example directory.
=> Search route

src/__tests__/indexes.ts
=> Add tests for update route

package.json, yarn.lock
=> Yarn update missing

README.md
- Changed titles, renamed some routes and types that were out of date
=> Changed titles, renamed some routes and types that were out of date

README.md, src/__tests__/indexes.ts, src/indexes.ts
=> Added Stats and Completed indexes

README.md, package.json, yarn.lock
NPM package is now called meilisearch and not @meilisearch/meili-api
=> NPM package name change

README.md, examples/search_example.js, src/__tests__/indexes.ts, src/__tests__/meili.ts, src/index.ts, src/indexes.ts
- renamed Index() to getIndex()
- renamed index.getIndex() to index.show()
- Replaced @memberof that were false
=> Index naming

README.md
=> Fix Getting Started in README

examples/small_index.js, src/indexes.ts, src/types.ts, tests/search_tests.ts
Tests on search. Tested a variety of combinations and did the tests with every auth key:
=> Search tests

tests/update_tests.ts
=> Tests on updates

package.json, tests/client_tests.ts, tests/search_tests.ts
- Changed version in package.json
- Changed tests that were breaking
=> Prepare v0.10

CHANGELOG.md
=> Changelogs for v0.10

.github/workflows/publish.yml
- Remove node
- Replaced build-ci with build script
- Npm publish now published at root
=> Removed download of node and fixed script and folder of publish

CHANGELOG.md, README.md, package.json, rollup.config.js
=> Fix typescript config overide by rollup

src/custom-errors/meilisearch-error.ts, tests/accept_new_fields_tests.ts, tests/attributes_for_faceting_tests.ts, tests/client_tests.ts, tests/displayed_attributes_tests.ts, tests/distinct_attribute_tests.ts, tests/documents_tests.ts, tests/ranking_rules_tests.ts, tests/search_tests.ts, tests/searchable_attributes_tests.ts, tests/settings_tests.ts, tests/stop_words_tests.ts, tests/synonyms_tests.ts, tests/update_tests.ts, tests/wait_for_pending_update_tests.ts
Refactor and updated tests.
They are still failing as the tests are performed on v0.10 and not v0.11.
=> Test compatibility with v0.11

.code-samples.meilisearch.yaml
=> Updated code samples

examples/search_example.js, examples/small_index.js
=> Improve examples

.code-samples.meilisearch.yaml
related to: meilisearch/documentation#405
=> Update code_sample of updateDocuments

.github/release-draft-template.yml
See https://github.com/release-drafter/release-drafter/issues/569
=> Use replacer to remove dependabot from contributors

README.md
I do not mention and explain the release-drafter workflow yet, I will do it in the next PR after discussing with @eskombro and @bidoubiwa.
This PR is only to keep the README up-to-date (because this process in the terminal is outdated now).
=> Update "Release" section in README

README.md
Change search usage in readme as it was missing the new method parameter
=> Change search usage in readme

CONTRIBUTING.md, package.json
=> Update the version for next release (v0.12.0)

README.md, package.json, src/index.ts, src/types.ts, tests/search_tests.ts, tests/typed_search_tests.ts, yarn.lock
In this PR
- Added documentation on how to use placeholder search
- Added tests on placeholder search
- Added acceptes type `null` for the query parameter
Fixes: #538 
@hubalt is this good enough documentation ?
=> Add placeholder search doc and tests

src/types.ts
Here ya go https://docs.meilisearch.com/references/stats.html#get-stats-of-all-indexes
=> Fix fieldsDistribution being typed as fieldsFrequency

tests/index_tests.ts
Update of the only failing tests for the upcomming MeiliSearch version https://github.com/meilisearch/MeiliSearch/releases/tag/v0.14.0rc0
=> Update index tests

package.json
- Change version in package.json
=> Upgrade to v14

.code-samples.meilisearch.yaml
=> Update code-samples for search parameters

README.md, tests/index_tests.ts, tests/search_tests.ts
This PR:
- should work locally with the [prerelease v0.15.0rc0](https://github.com/meilisearch/MeiliSearch/releases/tag/v0.15.0rc0)
⚠️ This PR should not be merged until the MeiliSearch's release v0.15.0 is out.
=> Changes about the MeiliSearch's next release (v0.15.0)

.code-samples.meilisearch.yaml
Add code samples and fixes : #626
=> Update code samples with dumps examples

README.md, src/meilisearch.ts, src/types.ts
This PR updates `isHealthy `method type signature according to discussion https://github.com/meilisearch/meilisearch-js/issues/647.
=> Update `isHealthy` method type signature

tests/env/express/public/index.html, tests/env/express/tests/client.test.js
- Try to remove the random failing error by adding a bigger timeOut 
Fixes: #622
=> Remove random failing test

tests/dump_tests.ts, tests/env/express/tests/client.test.js, tests/meilisearch-test-utils.ts
Add test util `waitForDumpProcessing`. It is a function only existing for test purposes. Naming can change. 
Fix failing tests
=> Improve dump tests

README.md
=> Update README.md with React Native compatibility

.code-samples.meilisearch.yaml
Update the following code samples 
- document addition in getting started
- searchable attribute
- displayed attribute
https://github.com/meilisearch/documentation/pull/571
https://github.com/meilisearch/integration-guides/issues/75
=> Update code samples searchabld and lazy index

jest.config.js
Update jsdom dom comment to be more accurate
=> Update jsdom comment

src/meilisearch.ts, tests/client_tests.ts
Related to #790 
- Fixed and added tests to prevent it from happening again
=> Fixes wrong key route

.github/dependabot.yml
see 
- https://github.com/meilisearch/meilisearch-js/issues/760
- https://github.com/meilisearch/meilisearch-js/pull/768
=> Add jest environment and prettier in ignore dependabot file

README.md, src/http-requests.ts, src/index.ts, src/types.ts, tests/attributes_for_faceting_tests.ts, tests/displayed_attributes_tests.ts, tests/distinct_attribute_tests.ts, tests/ranking_rules_tests.ts, tests/searchable_attributes_tests.ts
**Description**
Adding the possibility for the client to send body null.
Adding tests to check if nil could be sent properly.
=> Adding the possibility to send body null and tests

.code-samples.meilisearch.yaml
fixes: https://github.com/meilisearch/documentation/issues/933
=> Update client in code-samples

.github/dependabot.yml, .github/workflows/tests.yml, CONTRIBUTING.md, README.md, bors.toml, jest.config.js, package.json, yarn.lock
=> Remove guaranteed compatibility with versions to 10> and <15 

src/index.ts, src/meilisearch.ts, src/types.ts, tests/index_tests.ts
Relates to https://github.com/meilisearch/integration-guides/issues/107
=> Adding delete if exists methods

src/index.ts, src/meilisearch.ts, tests/unit_tests.ts
Changed the router to something more readable
fixes: #916
=> Fixes stats cors issue

src/index.ts, src/meilisearch.ts, tests/attributes_for_faceting_tests.ts, tests/client_tests.ts, tests/displayed_attributes_tests.ts, tests/distinct_attribute_tests.ts, tests/documents_tests.ts, tests/dump_tests.ts, tests/index_tests.ts, tests/ranking_rules_tests.ts, tests/search_tests.ts, tests/searchable_attributes_tests.ts, tests/settings_tests.ts, tests/stop_words_tests.ts, tests/synonyms_tests.ts, tests/typed_search_tests.ts, tests/unit_tests.ts, tests/update_tests.ts
=> Refactor tests

.code-samples.meilisearch.yaml, README.md, src/index.ts, src/types.ts, tests/env/node/getting_started.js, tests/search_tests.ts, tests/typed_search_tests.ts
- Remove facetFilters
- filter/facet on number are now doable
- test the array syntax on filter
- Some part of the code-samples are changed
=> Use filter

README.md, src/index.ts, src/types.ts, tests/stop_words_tests.ts, tests/synonyms_tests.ts
- Added tests on Synonyms and StopWords
- Created individual types for settings to avoid duplicated of types
- Added null as possible value for StopWords and Synonyms
=> Settings accepting null

README.md, src/types.ts, tests/dump_tests.ts, tests/search_tests.ts
Removed tests on GET until this is resolved: https://github.com/meilisearch/MeiliSearch/issues/1489
=> Facetsdistribution updates

.github/workflows/publish.yml
Reverts meilisearch/meilisearch-js#985
=> Revert "Change token in CI"

README.md, src/lib/meilisearch.ts, tests/client_tests.ts
Update the stats and version methods names as explained. Fixes #920
=> refactor(#920): Update the method names

.code-samples.meilisearch.yaml, README.md, src/lib/meilisearch.ts, tests/client_tests.ts, tests/documents_tests.ts, tests/env/browser/index.html, tests/env/typescript-browser/src/index.ts, tests/env/typescript-node/src/index.ts, tests/index_tests.ts, tests/meilisearch-test-utils.ts
=> Changes name of listIndexes to getIndexes

src/errors/http-error-handler.ts, src/errors/meilisearch-api-error.ts, src/errors/meilisearch-communication-error.ts, src/lib/http-requests.ts, src/lib/indexes.ts, src/lib/meilisearch.ts, src/types/types.ts, tests/client_tests.ts, tests/env/typescript-node/package.json, tests/env/typescript-node/yarn.lock, tests/meilisearch-test-utils.ts, tests/search_tests.ts, tsconfig.json
fixes: #1076 
- Remove unecessary type complexcity in MeiliSearchApiError
- Add explicit type comparison when Error are used for a specific purpose
- Fix tests and all occurrences of catch by adding an explicit any type
=> Fix unknown catch

src/errors/meilisearch-api-error.ts, src/lib/indexes.ts, src/lib/meilisearch.ts, src/types/types.ts, tests/client_tests.ts, tests/displayed_attributes_tests.ts, tests/distinct_attribute_tests.ts, tests/documents_tests.ts, tests/dump_tests.ts, tests/filterable_attributes_tests.ts, tests/get_or_create_tests.ts, tests/get_search_tests.ts, tests/index_tests.ts, tests/ranking_rules_tests.ts, tests/search_tests.ts, tests/searchable_attributes_tests.ts, tests/settings_tests.ts, tests/sortable_attributes_tests.ts, tests/stop_words_tests.ts, tests/synonyms_tests.ts, tests/typed_search_tests.ts, tests/update_tests.ts
=> Update fields in MeiliSearchApiError

.github/workflows/pre-release-tests.yml, .github/workflows/publish.yml, .github/workflows/tests.yml, CONTRIBUTING.md, README.md, bors.toml
=> Confirm node 16 compatibility

tests/settings_tests.ts
=> Skip randomly failing test

src/lib/http-requests.ts
=> Update authorization header

CONTRIBUTING.md
Add guide in CONTRIBUTING.md to release a beta version.
=> Add steps to release a beta version

.github/workflows/pre-release-tests.yml
Will be fixed when this PR is released in the next RC of meilisearch : https://github.com/meilisearch/MeiliSearch/pull/2056
=> Add tests to guarantee different headers are accepted

.github/workflows/pre-release-tests.yml, tests/env/browser/index.html, tests/env/express/public/headers.html, tests/env/express/public/index.html, tests/env/express/src/server.js, tests/env/express/tests/client.test.js
Check to avoid unexpected CORS errors
=> Add headers tests

README.md, src/lib/meilisearch.ts, tests/env/express/public/headers.html, tests/keys_tests.ts, tests/meilisearch-test-utils.ts
See https://github.com/meilisearch/MeiliSearch/pull/2054
=> Update result of getKeys route

tests/client_tests.ts, tests/dump_tests.ts, tests/index_tests.ts, tests/keys_tests.ts, tests/meilisearch-test-utils.ts
Thank you so much for contributing to MeiliSearch!
=> Changed wording of the variable names and test descriptions

src/types/types.ts
=> Complete details field in tasks

package.json
Update the version for the next release!
=> Update version for the next release (v0.25.0)

package.json, tests/displayed_attributes_tests.ts, tests/distinct_attribute_tests.ts, tests/documents_tests.ts, tests/filterable_attributes_tests.ts, tests/ranking_rules_tests.ts, tests/searchable_attributes_tests.ts, tests/settings_tests.ts, tests/sortable_attributes_tests.ts, tests/stop_words_tests.ts, tests/synonyms_tests.ts, tests/task_tests.ts, tests/wait_for_task.ts
The same resources in the tests were duplicated instead of required from the same fixture
=> Avoid duplication in tests

tests/get_search_tests.ts, tests/meilisearch-test-utils.ts, tests/search_tests.ts, tests/typed_search_tests.ts
Add tests on nested fields to ensure it is still maintained in meilisearch
=> Add tests on nested field support

.code-samples.meilisearch.yaml
as per [this issue](https://github.com/meilisearch/integration-guides/issues/190)
new code samples are introduced and one is updated.
=> Update the code samples with highlight and crop

.code-samples.meilisearch.yaml
Fixes the code sample for `getDocument` on indexes
=> Fix getDocument code sample for documenation

package.json
Fix the version introduce by this PR: https://github.com/meilisearch/meilisearch-js/pull/1218
=> BugFix: Update version for the next release (meilisearch-js v0.25.1) 

src/lib/clients/client.ts, src/lib/indexes.ts
=> Fix outdated references to updates in comments

src/types/types.ts
Fixes #1222 
https://github.com/meilisearch/meilisearch-js/issues/1222
=> FIX-1222 Update EnqueuedTask to be in line with spec

.code-samples.meilisearch.yaml
based on https://github.com/meilisearch/documentation/pull/1544/files#
=> Update primary key code-samples

src/indexes.ts, tests/index.test.ts
Fixes #1040
Since index creation is asynchronous it is never initialized with the knowledge of `createdAt` or `updatedAt` that information can only be obtained through `getRawInfo`
=> Updated created at in index

src/errors/meilisearch-api-error.ts, src/errors/meilisearch-communication-error.ts, src/errors/meilisearch-error.ts, src/errors/meilisearch-timeout-error.ts, tests/errors.test.ts
=> Add prototype setting for meili errors to allow instanceof operator

.github/scripts/beta-docker-version.sh, .github/workflows/beta-tests.yml
Adds a CI that triggers the tests for the correct beta feature
=> Add beta testing in CI

.code-samples.meilisearch.yaml
Index should be `movies` but was `movie`.
=> Fix code sample from the getting started

src/indexes.ts
Fixes #1346 
- It modifies some returns
=> docs: modification of certain returns

package.json, src/package-version.ts
This version introduces:
- `pagination` setting
- `faceting` setting
- Changing the dates that were kept in string format to Date formats
- Changed `Task` and `EnqueuedTask` to classes instead of objects
=> Update version for the next release (v0.29.0)

docker-compose.yml, tests/utils/meilisearch-test-utils.ts
Fixes #1356 
- Changed MEILISEARCH_HOST to MEILISEARCH_URL
=> Changed MEILISEARCH_HOST to MEILISEARCH_URL

.code-samples.meilisearch.yaml
Fixes: #1364 
If I understand, the request was to simply add two matching strategies to this file. Assuming it was this easy I suppose I did something wrong, but I would like to see if this is what the issuer meant.
=> docs: add parameter samples in v0.29 release

package.json, src/package-version.ts
Updating version for the next release
=> Update version for the next release (v0.29.1)

.code-samples.meilisearch.yaml
Add the changes requested https://github.com/meilisearch/integration-guides/issues/224#issuecomment-1328645858
=> Fix canceled by code sample

.code-samples.meilisearch.yaml
See title, stumbled upon this in the main docs.
=> Fix missing comma in update settings example code

src/indexes.ts
=> Ensure the document type provided to the search method is a Record

tests/search.test.ts
As per #1435 
This PR adds additional tests to ensure the types are working as expected
=> Add additional tests on pagination typing

src/types/types.ts
Some additional types useful in some usecases.
=> Add MultiSearchQuery and MultiSearchResult types

src/errors/meilisearch-communication-error.ts, src/http-requests.ts
=> Remove conditionnal loading for fetch polyfill

src/indexes.ts, tests/typo_tolerance.test.ts
Following #1455, this PR fixes the test of the PR.
=> Fix get typo tolerance return type

src/clients/client.ts, src/types/types.ts, tests/keys.test.ts
No
- Fix typos for Key type param, "updateAt" should be "updatedAt".
=> Fix Key type param typos.

.code-samples.meilisearch.yaml
Update code-samples accordingly to these changes: https://github.com/meilisearch/integration-guides/issues/282
=> Update code-samples for Meilisearch v1.3

README.md
- Updates README: adds missing link to searchForFacetValues
=> Add missing link to searchForFacetValues

package.json, src/package-version.ts
Bump version to version 0.34.1
=> chore: bump to version 0.34.1

.github/workflows/tests.yml, README.md, jest.config.js
Add Codecov
Fixes #1566 
-  Add CodeCov to this repository.
-  Add the CodeCov badge on this repository README.md
=> Add codecov

README.md
=> Fix filterable attribute example in README.md

.code-samples.meilisearch.yaml
Related to https://github.com/meilisearch/documentation/issues/2556
=> Code samples v1.4

.code-samples.meilisearch.yaml
Based on https://github.com/meilisearch/documentation/issues/2659
=> Add code samples v1.6.0

src/types/types.ts, tests/get_search.test.ts, tests/search.test.ts
Fixes #1674
- Addition of a new `distinct` attribute on search (both on POST and GET)
- Addition of the related tests
=> feat: add  attribute at search

.github/scripts/check-release.sh
Follwoing change in this PR: https://github.com/meilisearch/meilisearch-js/pull/1663
=> Fix release version check script

src/types/types.ts, tests/embedders.test.ts
Fixes #1685
Update the embedders types + tests according to v1.10 changes
=> Add AI-powered search changes related to v1.10

.github/dependabot.yml
=> Let dependabot create a single PR for multiple dependencies

package.json, rollup.config.js, yarn.lock
- recent dependabot updates introduced peer dependency incompat, this PR aims to fix warning
=> Update wrong rollup terser dependency

.code-samples.meilisearch.yaml
Add docs code samples for v1.12
⚠️ I initially created the PR to merge into `main` instead of `bump-*`, tests may fail because of this.
=> Add 1.12 code samples

CONTRIBUTING.md, README.md
=> Remove mention of support of Node 14 and 16

tsconfig.build.json, tsconfig.json
=> Fix lack of source maps in ESM output

README.md, tests/__snapshots__/settings.test.ts.snap, tests/documents.test.ts, tests/embedders.test.ts, tests/get_search.test.ts, tests/search.test.ts, tests/settings.test.ts
=> Remove `vectorStore` experimental setting

.github/release-draft-template.yml, .github/workflows/tests.yml, CONTRIBUTING.md, README.md, bors.toml
=> Remove BORS, enable merge queues in actions

package.json, tests/client.test.ts, tests/unit.test.ts, tests/utils/meilisearch-test-utils.ts, yarn.lock
- update ESLint and plugins and Vitest
- adapt code
=> Update Vitest, ESLint and plugins, adapt code

src/types/experimental-features.ts, tests/experimental-features.test.ts
Update API to allow toggling v1.16 experimental features.
=> Update experimental features to v1.16
